import Link from "next/link";
import { InnerFooter, InnerHeader } from "../../components/InnerChrome";
import { FaqSection } from "../../components/FaqSection";

export const metadata = { title: "Specialty Contact Lenses | Cosmopolitan Eyecare" };

export default function SpecialtyLensesPage() {
  return <><InnerHeader /><main id="main-content" className="detail-page"><section className="specialty-hero specialty-lenses-hero"><Link href="/" className="back-link">← Cosmopolitan Eyecare</Link><p className="kicker">SPECIALTY CONTACT LENSES</p><h1>Vision should fit your <em>life.</em></h1><p className="detail-lede">When standard lenses are not the answer, an experienced fitting process can make a meaningful difference in comfort, clarity, and confidence.</p></section><section className="detail-band"><p className="section-label">MADE FOR THE DETAILS</p><div><h2>Beyond the standard fit.</h2><p>Cosmopolitan Eyecare offers a detailed specialty lens conversation for patients who need more attention to vision, comfort, and fit than a standard appointment may provide.</p></div></section><section className="steps"><p className="section-label">THE FITTING EXPERIENCE</p><ol><li><span>01</span><div><h3>Start with your needs</h3><p>Talk about how you see, work, move, and feel in your current lenses.</p></div></li><li><span>02</span><div><h3>Explore the right option</h3><p>Receive a fitting approach tailored to your eyes and goals.</p></div></li><li><span>03</span><div><h3>Leave with confidence</h3><p>Get clear guidance and continued support from our team.</p></div></li></ol></section><FaqSection items={[{question:"What makes a specialty contact lens fitting different?",answer:"The fitting process is individualized around your vision needs, comfort, eye health, and the specific lens options the provider recommends."},{question:"Can I ask about scleral lenses?",answer:"Yes. Scleral contact lenses are included in Cosmopolitan Eyecare&apos;s service inventory. Contact the practice to discuss the appropriate appointment type."},{question:"Do I need an appointment?",answer:"Contact the practice to share your needs and confirm the appropriate appointment path."}]} /><a className="service-contact" href="https://www.lenscrafters.com/webapp/wcs/stores/servlet/ScheduleExamView?catalogId=11651&langId=-1&storeId=10851&storeNumber=3725" target="_blank" rel="noreferrer">Book an appointment <span>↗</span></a></main><InnerFooter /></>;
}
