import Link from "next/link";
import { InnerFooter, InnerHeader } from "../../components/InnerChrome";
import { FaqSection } from "../../components/FaqSection";

export const metadata = { title: "Ocular Aesthetics | Cosmopolitan Eyecare" };

export default function AestheticsPage() {
  return <><InnerHeader /><main id="main-content" className="detail-page"><section className="specialty-hero aesthetics-hero"><Link href="/" className="back-link">← Cosmopolitan Eyecare</Link><p className="kicker">OCULAR AESTHETICS</p><h1>Care for the eyes that say <em>everything.</em></h1><p className="detail-lede">A dedicated space for eye-area aesthetics, grounded in the same careful clinical perspective as the rest of your care.</p></section><section className="detail-band"><p className="section-label">A CONSIDERED APPROACH</p><div><h2>Refinement, not reinvention.</h2><p>Cosmopolitan Eyecare&apos;s aesthetic pathway brings an eye-care perspective to concerns around the eye area. Your consultation begins with your goals, comfort, and a clear discussion of the most appropriate next step.</p></div></section><section className="quote"><p>“The most effective care feels personal, precise, and entirely your own.”</p></section><FaqSection items={[{question:"What happens during an ocular aesthetics consultation?",answer:"A consultation is an opportunity to discuss your goals and questions with the practice. The team can explain the appropriate next step and whether an in-person evaluation is needed."},{question:"Who provides aesthetic care?",answer:"The Cosmopolitan Eyecare team will guide you to the appropriate consultation and explain what is suitable for your concerns."},{question:"Does this page provide treatment advice?",answer:"No. This page is educational and does not replace a personal consultation with a qualified provider."}]} /><a className="service-contact" href="https://www.lenscrafters.com/webapp/wcs/stores/servlet/ScheduleExamView?catalogId=11651&langId=-1&storeId=10851&storeNumber=3725" target="_blank" rel="noreferrer">Book an appointment <span>↗</span></a></main><InnerFooter /></>;
}
