import Link from "next/link";
import { InnerFooter, InnerHeader } from "../../components/InnerChrome";
import { FaqSection } from "../../components/FaqSection";

const resources = [
  { category: "Dry eye", title: "Understanding dry eye symptoms", copy: "A patient-friendly starting point for dry, irritated, burning, watery, or changing vision concerns.", href: "/dry-eye" },
  { category: "Contact lenses", title: "Care that starts with the right fit", copy: "Explore the specialty lens pathway and learn how to start a fitting conversation.", href: "/specialty-contact-lenses" },
  { category: "Preventive care", title: "The value of a comprehensive eye exam", copy: "Learn where preventive vision and eye-health care fit into your overall wellness.", href: "/care/comprehensive-eye-exams" },
  { category: "Conditions", title: "Trusted national eye-health information", copy: "Browse broader eye-condition education from the National Eye Institute.", href: "https://www.nei.nih.gov/eye-health-information", external: true },
] as const;

export const metadata = { title: "Eye Health Resources | Cosmopolitan Eyecare", description: "Eye-health education and care pathways from Cosmopolitan Eyecare.", robots: { index: false, follow: false } };

export default function EyeHealthPage() {
  return <><InnerHeader /><main id="main-content" className="detail-page resource-page"><section className="specialty-hero"><Link href="/" className="back-link">← Cosmopolitan Eyecare</Link><p className="kicker">EYE HEALTH RESOURCES</p><h1>Better information makes <em>better decisions.</em></h1><p className="detail-lede">Clear, practical eye-health education from Cosmopolitan Eyecare—with links to trusted external resources when you want to go deeper.</p></section><section className="resource-grid"><p className="section-label">START HERE</p>{resources.map((resource, index) => resource.href.startsWith("http") ? <a className="resource-card" href={resource.href} target="_blank" rel="noreferrer" key={resource.title}><span>0{index + 1} · {resource.category}</span><h2>{resource.title}</h2><p>{resource.copy}</p><b>↗</b></a> : <Link className="resource-card" href={resource.href} key={resource.title}><span>0{index + 1} · {resource.category}</span><h2>{resource.title}</h2><p>{resource.copy}</p><b>→</b></Link>)}</section><section className="resource-note"><p className="section-label">A NOTE ON HEALTH INFORMATION</p><p>Educational resources can help you prepare for a conversation, but they do not replace personal medical advice. Contact the practice if you have concerns about your vision or eye comfort.</p><Link href="/contact">Contact the practice →</Link></section><FaqSection items={[{question:"Where should I start if I have a new eye concern?",answer:"If you have a new or changing concern, contact the practice and explain what you are experiencing. The team can help you identify the appropriate appointment path."},{question:"Can online resources replace an eye exam?",answer:"No. Online information can help you prepare questions, but it cannot diagnose an eye condition or replace a comprehensive examination."},{question:"What should I bring to an eye appointment?",answer:"Bring your current glasses or contact lens information, a list of medications, and any questions about changes in your vision or comfort."}]} /></main><InnerFooter /></>;
}
