import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings & homepage",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Internal title", type: "string", initialValue: "Cosmopolitan Eyecare" }),
    defineField({ name: "heroEyebrow", title: "Homepage hero eyebrow", type: "string" }),
    defineField({ name: "heroTitle", title: "Homepage hero title", type: "string" }),
    defineField({ name: "heroEmphasis", title: "Homepage hero italic line", type: "string" }),
    defineField({ name: "heroLede", title: "Homepage hero supporting copy", type: "text", rows: 4 }),
    defineField({ name: "practiceEyebrow", title: "Practice credibility eyebrow", type: "string", group: "homepage" }),
    defineField({ name: "practiceTitle", title: "Practice credibility title", type: "string", group: "homepage" }),
    defineField({ name: "practiceEmphasis", title: "Practice credibility italic words", type: "string", group: "homepage" }),
    defineField({ name: "practiceBody", title: "Practice credibility copy", type: "text", rows: 4, group: "homepage" }),
    defineField({ name: "careEyebrow", title: "Care pathways eyebrow", type: "string", group: "homepage" }),
    defineField({ name: "careTitle", title: "Care pathways title", type: "string", group: "homepage" }),
    defineField({ name: "careEmphasis", title: "Care pathways italic words", type: "string", group: "homepage" }),
    defineField({ name: "careBody", title: "Care pathways copy", type: "text", rows: 4, group: "homepage" }),
    defineField({ name: "proofEyebrow", title: "Doctors section eyebrow", type: "string", group: "homepage" }),
    defineField({ name: "proofTitle", title: "Doctors section title", type: "string", group: "homepage" }),
    defineField({ name: "proofEmphasis", title: "Doctors section italic words", type: "string", group: "homepage" }),
    defineField({ name: "proofBody", title: "Doctors section copy", type: "text", rows: 4, group: "homepage" }),
    defineField({ name: "visitEyebrow", title: "Visit section eyebrow", type: "string", group: "homepage" }),
    defineField({ name: "visitDescription", title: "Visit section appointment copy", type: "text", rows: 3, group: "homepage" }),
    defineField({ name: "reviewsEyebrow", title: "Patient stories eyebrow", type: "string", group: "homepage" }),
    defineField({ name: "reviewsTitle", title: "Patient stories title", type: "string", group: "homepage" }),
    defineField({ name: "reviewsEmphasis", title: "Patient stories italic words", type: "string", group: "homepage" }),
    defineField({ name: "reviewsBody", title: "Patient stories copy", type: "text", rows: 4, group: "homepage" }),
    defineField({ name: "phone", title: "Primary phone", type: "string" }),
    defineField({ name: "address", title: "Practice address", type: "text", rows: 3 }),
    defineField({ name: "bookingUrl", title: "Appointment booking URL", type: "url" }),
  ],
  groups: [{ name: "homepage", title: "Homepage sections", default: true }, { name: "practice", title: "Contact details" }],
  preview: { select: { title: "title" } },
});
