import Link from "next/link";
import { InnerFooter, InnerHeader } from "../../components/InnerChrome";
import { FaqSection } from "../../components/FaqSection";

export const metadata = { title: "Dry Eye Care | Cosmopolitan Eyecare" };

export default function DryEyePage() {
  return <><InnerHeader /><main id="main-content" className="detail-page"><section className="specialty-hero dry-eye-hero"><Link href="/" className="back-link">← Cosmopolitan Eyecare</Link><p className="kicker">DRY EYE CENTER</p><h1>Relief begins with being <em>heard.</em></h1><p className="detail-lede">Persistent dry, irritated, or tired eyes deserve more than a quick fix. Our dry eye center is designed to help identify the factors behind your symptoms and discuss a thoughtful next step.</p></section><section className="detail-band"><p className="section-label">A MORE COMPLETE CONVERSATION</p><div><h2>See beyond the surface.</h2><p>Dry eye can have more than one contributor. A focused visit makes room to talk through your symptoms, visual demands, and eye-health history before discussing a care plan.</p></div></section><section className="steps"><p className="section-label">YOUR PATH</p><ol><li><span>01</span><div><h3>Tell us what is changing</h3><p>Start with the symptoms affecting your everyday life.</p></div></li><li><span>02</span><div><h3>Get a focused evaluation</h3><p>Explore the right clinical conversation with the care team.</p></div></li><li><span>03</span><div><h3>Choose a next step</h3><p>Move forward with a plan that makes sense for you.</p></div></li></ol></section><FaqSection items={[{ question: "What are common dry eye symptoms?", answer: "Dry, scratchy, burning, red, or watery eyes and blurry vision can all be associated with dry eye. An eye-care professional can help determine what may be contributing to your symptoms." }, { question: "When should I schedule a dry eye evaluation?", answer: "If eye discomfort or changing vision is persistent, interferes with daily activities, or concerns you, contact the practice to discuss the most appropriate visit." }, { question: "Does this page provide medical advice?", answer: "No. This is general educational information and is not a diagnosis or a substitute for a personal evaluation by an eye-care professional." }]} /><a className="service-contact" href="https://www.lenscrafters.com/webapp/wcs/stores/servlet/ScheduleExamView?catalogId=11651&langId=-1&storeId=10851&storeNumber=3725" target="_blank" rel="noreferrer">Book a dry eye consultation <span>↗</span></a></main><InnerFooter /></>;
}
