import type { Metadata } from "next";
import Link from "next/link";
import { permanentRedirect } from "next/navigation";
import { InnerFooter, InnerHeader } from "../../../components/InnerChrome";
import { FaqSection } from "../../../components/FaqSection";
import { siteUrl } from "../../../lib/site-config";

const services = [
  "Comprehensive eye exams", "Myopia management", "Computer vision", "Seasonal allergies", "Dry eye treatment", "OptiLight IPL", "Perimenopause and menopause dry eye", "Contact lens exams", "Specialty contact lenses", "Scleral contact lenses", "Eye infections", "Ocular disease management", "Diabetic-related eye exams", "Common eye disorders", "Eye emergencies", "LASIK evaluations", "Cataracts", "Macular degeneration", "Glaucoma", "Ocular aesthetics",
] as const;

const slug = (name: string) => name.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const primarySpecialtyRoutes: Record<string, string> = {
  "dry-eye-treatment": "/dry-eye",
  "specialty-contact-lenses": "/specialty-contact-lenses",
  "ocular-aesthetics": "/aesthetics",
};

const serviceContent: Record<(typeof services)[number], { lede: string; heading: string; detail: string }> = {
  "Comprehensive eye exams": { lede: "A thorough eye exam creates space to talk about vision, comfort, eye health, and the changes you have noticed.", heading: "A clear view of the full picture.", detail: "Your visit can address prescription needs alongside the broader questions that help guide preventive eye care." },
  "Myopia management": { lede: "For patients and families navigating nearsightedness, a proactive conversation can make future care feel more understandable.", heading: "Keep the long view in focus.", detail: "Share changes in vision, daily visual demands, and family concerns so the team can guide the appropriate evaluation." },
  "Computer vision": { lede: "Long screen days can leave eyes feeling tired, strained, or less comfortable. Start with the habits and symptoms affecting your workday.", heading: "Make screen time easier on your eyes.", detail: "A conversation about visual comfort, work setup, and prescription needs can clarify your next step." },
  "Seasonal allergies": { lede: "Itchy, watery, or irritated eyes can make seasonal changes feel more disruptive. The right visit begins with what you are experiencing.", heading: "Relief starts with context.", detail: "Describe when symptoms begin, what makes them worse, and how they affect your eyes and everyday comfort." },
  "Dry eye treatment": { lede: "Persistent dryness, burning, fluctuating vision, or tired eyes deserve a focused conversation—not a one-size-fits-all answer.", heading: "Look beyond the surface.", detail: "A dry-eye evaluation can help the care team understand your symptoms and discuss an appropriate plan." },
  "OptiLight IPL": { lede: "If dry-eye discomfort is affecting your day, ask the team whether an OptiLight IPL conversation may be appropriate for you.", heading: "Explore the options with clarity.", detail: "Your appointment is a chance to review symptoms, eye-health history, and the care pathways the practice offers." },
  "Perimenopause and menopause dry eye": { lede: "Hormonal changes can coincide with changing eye comfort. Bring the whole picture to a focused dry-eye conversation.", heading: "A more connected conversation.", detail: "Share the changes you notice in comfort, vision, and daily routine so the team can help guide the next step." },
  "Contact lens exams": { lede: "A contact lens exam considers the way you see, work, move, and feel in your lenses—not only the prescription.", heading: "Comfort and clarity belong together.", detail: "Use your visit to talk through wear time, comfort, vision goals, and any changes since your last fitting." },
  "Specialty contact lenses": { lede: "When standard lenses are not meeting your visual or comfort needs, a more individualized fitting conversation can help.", heading: "A fit made for the details.", detail: "The team can discuss your current experience, goals, and the specialty lens options that may fit your needs." },
  "Scleral contact lenses": { lede: "Scleral lens conversations begin with your eyes, visual goals, and comfort—not a generic fitting checklist.", heading: "Explore a more tailored fit.", detail: "Ask about the appropriate appointment path and what to bring from your current lens experience." },
  "Eye infections": { lede: "New redness, discharge, discomfort, or other concerning eye symptoms deserve prompt attention from an eye-care professional.", heading: "Know when to reach out.", detail: "Call the practice to explain what is changing and receive guidance on the appropriate next step." },
  "Ocular disease management": { lede: "Ongoing eye-health care works best when you understand what is being monitored and why it matters.", heading: "Stay connected to your eye health.", detail: "Bring questions, medication information, and any changes in vision or comfort to your appointment." },
  "Diabetic-related eye exams": { lede: "Diabetes can affect eye health, which makes regular eye care an important part of your broader wellness routine.", heading: "Make eye health part of the plan.", detail: "A dedicated eye exam creates a chance to discuss your eye health, vision, and relevant health history." },
  "Common eye disorders": { lede: "When something about your vision or eye comfort feels different, a clear conversation can help identify the right next step.", heading: "Bring the questions with you.", detail: "Share what has changed, when it began, and how it affects daily life so the team can guide your visit." },
  "Eye emergencies": { lede: "Sudden vision changes, significant pain, or an eye injury may need urgent attention. Do not wait for a routine appointment.", heading: "Act promptly when symptoms are urgent.", detail: "Call the practice immediately for guidance; if you are experiencing a medical emergency, seek emergency care." },
  "LASIK evaluations": { lede: "Considering LASIK starts with a careful review of your vision, eye health, and what you hope to achieve.", heading: "Start with an informed evaluation.", detail: "Use your appointment to discuss whether a refractive-surgery evaluation is the appropriate next step for you." },
  "Cataracts": { lede: "Changes in glare, clarity, or daily vision are worth discussing with an eye-care professional.", heading: "Understand what has changed.", detail: "A comprehensive eye-care conversation can help clarify what you are noticing and the appropriate follow-up." },
  "Macular degeneration": { lede: "Central vision changes deserve timely attention and a clear conversation about your eye health.", heading: "Keep changes in view.", detail: "Contact the practice if you notice changing central vision or have questions about monitoring and follow-up." },
  "Glaucoma": { lede: "Glaucoma care and monitoring begin with regular eye-health conversations and an understanding of your individual history.", heading: "Make monitoring feel manageable.", detail: "Bring your questions and relevant medical information so the team can guide the appropriate evaluation." },
  "Ocular aesthetics": { lede: "Eye-area aesthetics deserve the same thoughtful, personalized conversation as every other part of your care.", heading: "Refinement starts with listening.", detail: "Discuss your goals, comfort, and questions so the team can guide you to the appropriate consultation." },
};

const serviceGuidance: Record<(typeof services)[number], { rightFor: string; prepare: string; related: readonly (readonly [string, string])[] }> = {
  "Comprehensive eye exams": { rightFor: "Annual preventive care, prescription changes, and questions about vision or eye comfort.", prepare: "Bring current glasses or contact lens details, medication information, and a note of any changes you have noticed.", related: [["Contact lens exams", "/care/contact-lens-exams"], ["Medical eye care", "/care/ocular-disease-management"]] },
  "Myopia management": { rightFor: "Children, teens, and families looking for a thoughtful conversation about changing nearsightedness.", prepare: "Bring prior prescriptions, family eye-health history if known, and questions about school, screen use, or visual demands.", related: [["Comprehensive eye exams", "/care/comprehensive-eye-exams"], ["Computer vision", "/care/computer-vision"]] },
  "Computer vision": { rightFor: "People whose screen-heavy days are accompanied by visual fatigue, strain, or changing comfort.", prepare: "Note when symptoms occur, your daily screen demands, and whether glasses or contact lenses change the experience.", related: [["Comprehensive eye exams", "/care/comprehensive-eye-exams"], ["Dry eye treatment", "/dry-eye"]] },
  "Seasonal allergies": { rightFor: "Patients whose eye comfort changes with seasons, environments, or recurring irritation.", prepare: "Share what you are noticing, when it began, and any products or routines you have already tried.", related: [["Eye infections", "/care/eye-infections"], ["Comprehensive eye exams", "/care/comprehensive-eye-exams"]] },
  "Dry eye treatment": { rightFor: "Persistent dryness, burning, fluctuating vision, redness, or discomfort that affects daily life.", prepare: "Bring a list of symptoms, medications, current eye drops, contact lens habits, and the times of day discomfort is most noticeable.", related: [["Dry Eye Center", "/dry-eye"], ["OptiLight IPL", "/care/optilight-ipl"]] },
  "OptiLight IPL": { rightFor: "Patients who have discussed dry-eye concerns and want to understand whether this treatment conversation is appropriate.", prepare: "Bring your dry-eye history, current routines, and questions about expected next steps to a focused consultation.", related: [["Dry eye treatment", "/dry-eye"], ["Dry Eye Center", "/dry-eye"]] },
  "Perimenopause and menopause dry eye": { rightFor: "People noticing a change in eye comfort alongside hormonal or life-stage changes.", prepare: "Share the pattern of symptoms, current medications, and anything that seems to improve or worsen eye comfort.", related: [["Dry eye treatment", "/dry-eye"], ["Eye health resources", "/eye-health"]] },
  "Contact lens exams": { rightFor: "New and established wearers seeking clear, comfortable vision in everyday contact lenses.", prepare: "Bring current lens boxes or prescription information and be ready to discuss wear time, comfort, and visual goals.", related: [["Specialty contact lenses", "/specialty-contact-lenses"], ["Scleral contact lenses", "/care/scleral-contact-lenses"]] },
  "Specialty contact lenses": { rightFor: "Patients whose visual, comfort, or fitting needs call for a more individualized lens conversation.", prepare: "Bring your current lenses or records when possible and describe what is and is not working in daily life.", related: [["Scleral contact lenses", "/care/scleral-contact-lenses"], ["Contact lens exams", "/care/contact-lens-exams"]] },
  "Scleral contact lenses": { rightFor: "People exploring a specialty lens option and seeking guidance on the appropriate fitting pathway.", prepare: "Bring current lens information, prior fitting records if available, and specific questions about vision and comfort.", related: [["Specialty contact lenses", "/specialty-contact-lenses"], ["Contact lens exams", "/care/contact-lens-exams"]] },
  "Eye infections": { rightFor: "New redness, discharge, irritation, or other changes that may need prompt professional attention.", prepare: "Call first to describe symptoms and timing; do not wait for a routine visit if symptoms are concerning.", related: [["Eye emergencies", "/care/eye-emergencies"], ["Contact & visit", "/contact"]] },
  "Ocular disease management": { rightFor: "Patients who need ongoing monitoring or have questions about an eye-health condition.", prepare: "Bring medications, relevant health information, and questions about changes in vision, comfort, or prior care.", related: [["Diabetic-related eye exams", "/care/diabetic-related-eye-exams"], ["Glaucoma", "/care/glaucoma"]] },
  "Diabetic-related eye exams": { rightFor: "People with diabetes who need eye-health care as part of their broader wellness plan.", prepare: "Bring relevant medical history, current medication information, and any recent changes in vision.", related: [["Ocular disease management", "/care/ocular-disease-management"], ["Comprehensive eye exams", "/care/comprehensive-eye-exams"]] },
  "Common eye disorders": { rightFor: "Anyone seeking a clearer next step after noticing a change in vision, comfort, or eye appearance.", prepare: "Make a brief note of what changed, when it started, and how it affects work, driving, reading, or daily life.", related: [["Eye emergencies", "/care/eye-emergencies"], ["Medical eye care", "/care/ocular-disease-management"]] },
  "Eye emergencies": { rightFor: "Sudden vision changes, significant pain, injury, or symptoms that should not wait for a routine appointment.", prepare: "Call the practice immediately for guidance. For a medical emergency, seek emergency care or call 911.", related: [["Contact & visit", "/contact"], ["Eye infections", "/care/eye-infections"]] },
  "LASIK evaluations": { rightFor: "People considering whether a refractive-surgery evaluation may fit their vision goals and eye-health history.", prepare: "Bring your current prescription, lens history, and questions about daily visual demands and expectations.", related: [["Comprehensive eye exams", "/care/comprehensive-eye-exams"], ["Contact lens exams", "/care/contact-lens-exams"]] },
  "Cataracts": { rightFor: "People noticing changes in glare, clarity, contrast, or day-to-day vision.", prepare: "Describe when changes are most noticeable and bring information about current glasses, medications, and prior eye care.", related: [["Comprehensive eye exams", "/care/comprehensive-eye-exams"], ["Medical eye care", "/care/ocular-disease-management"]] },
  "Macular degeneration": { rightFor: "Patients with central-vision changes or questions about monitoring and eye-health follow-up.", prepare: "Call promptly for new or changing symptoms and bring relevant history, medications, and previous eye-care records.", related: [["Ocular disease management", "/care/ocular-disease-management"], ["Eye emergencies", "/care/eye-emergencies"]] },
  "Glaucoma": { rightFor: "Patients seeking regular eye-health monitoring or a clearer understanding of their personal follow-up needs.", prepare: "Bring medication information, relevant family history if known, and questions about prior testing or recommendations.", related: [["Ocular disease management", "/care/ocular-disease-management"], ["Comprehensive eye exams", "/care/comprehensive-eye-exams"]] },
  "Ocular aesthetics": { rightFor: "People interested in an eye-area aesthetics consultation grounded in a clear, personal discussion of goals.", prepare: "Bring questions, your goals for the visit, and any relevant eye-health or treatment history.", related: [["Ocular aesthetics", "/aesthetics"], ["Contact & visit", "/contact"]] },
};

export const dynamicParams = false;
export function generateStaticParams() { return services.map((service) => ({ service: slug(service) })); }

export async function generateMetadata({ params }: { params: Promise<{ service: string }> }): Promise<Metadata> {
  const { service } = await params;
  const matchedService = services.find((item) => slug(item) === service);
  const name = matchedService ?? "Care";
  return { title: `${name} | Cosmopolitan Eyecare`, description: matchedService ? serviceContent[matchedService].lede : `Learn about ${name} at Cosmopolitan Eyecare in Midtown Manhattan.` };
}

export default async function ServicePage({ params }: { params: Promise<{ service: string }> }) {
  const { service } = await params;
  if (primarySpecialtyRoutes[service]) permanentRedirect(primarySpecialtyRoutes[service]);
  const name = services.find((item) => slug(item) === service);
  if (!name) return null;
  const content = serviceContent[name];
  const guide = serviceGuidance[name];
  const serviceSchema = { "@context": "https://schema.org", "@type": "Service", name, description: content.lede, serviceType: name, provider: { "@id": `${siteUrl}/#practice` }, areaServed: { "@type": "City", name: "New York" } };
  return <><InnerHeader /><main id="main-content" className="detail-page service-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} /><section className="service-hero"><Link href="/services" className="back-link">← All services</Link><p className="kicker">COSMOPOLITAN EYECARE · SERVICE GUIDE</p><h1>{name}</h1><p className="detail-lede">{content.lede}</p><div className="service-hero-mark" aria-hidden="true"><span>CE</span><i /></div></section><section className="detail-band"><p className="section-label">WHAT TO EXPECT</p><div><h2>{content.heading}</h2><p>{content.detail}</p></div></section><section className="visit-context"><p className="section-label">PLAN YOUR VISIT</p><div><article><h2>Who this is for</h2><p>{guide.rightFor}</p></article><article><h2>How to prepare</h2><p>{guide.prepare}</p></article><article><h2>Related care</h2><p>{guide.related.map(([label, href]) => <Link href={href} key={href}>{label} <span>→</span></Link>)}</p></article></div></section><section className="service-promises"><article><span>01</span><h3>Personal attention</h3><p>Start with the details that matter to you—not a one-size-fits-all script.</p></article><article><span>02</span><h3>Clear information</h3><p>Understand your options and the purpose of your next step.</p></article><article><span>03</span><h3>Connected care</h3><p>Move easily between related services, resources, and the team.</p></article></section><section className="steps"><p className="section-label">YOUR NEXT STEP</p><ol><li><span>01</span><div><h3>Start with your concerns</h3><p>Share what is affecting your vision, comfort, or eye health.</p></div></li><li><span>02</span><div><h3>Talk with the care team</h3><p>Find the right appointment or consultation path for your needs.</p></div></li><li><span>03</span><div><h3>Make an informed plan</h3><p>Receive guidance tailored to your individual care goals.</p></div></li></ol></section><FaqSection items={[{ question: `What should I expect from a ${name.toLowerCase()} visit?`, answer: `${content.detail} Individual recommendations depend on your eye health, symptoms, and goals.` }, { question: "How do I know which appointment to book?", answer: "Contact the practice and share what you are experiencing. The team can help guide you to the most appropriate appointment type." }, { question: "Is this page medical advice?", answer: "No. Information on this site is educational only and does not replace a personal evaluation by an eye-care professional." }]} /><Link href="/contact" className="service-contact">Contact Cosmopolitan Eyecare <span>→</span></Link></main><InnerFooter /></>;
}
